# Generated by Django 5.1.3 on 2024-11-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="actif",
            field=models.BooleanField(default=False),
        ),
    ]
