# Generated by Django 5.1.3 on 2024-11-16 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_remove_project_contributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("BACKEND", "Back-end"),
                    ("FRONTEND", "Front-end"),
                    ("IOS", "iOS"),
                    ("ANDROID", "Android"),
                ],
                default=django.utils.timezone.now,
                max_length=12,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="actif",
            field=models.BooleanField(default=True),
        ),
    ]
