# Generated by Django 5.1.3 on 2024-11-18 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_alter_project_description_issue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="project_id",
            new_name="project",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="author",
        ),
    ]
