# Generated by Django 5.1.3 on 2024-11-18 21:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_rename_project_id_issue_project_remove_issue_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_issues",
                to="projects.contributor",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="assigned_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_issues",
                to="projects.contributor",
            ),
        ),
    ]
