# Generated by Django 5.1.3 on 2024-11-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_be_contacted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_data_be_shared",
            field=models.BooleanField(default=True),
        ),
    ]
