# Generated by Django 5.1.3 on 2024-11-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_user_can_be_contacted_user_can_data_be_shared"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="can_be_contacted",
            field=models.BooleanField(default=True),
        ),
    ]
