# Generated by Django 5.1.3 on 2024-11-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_user_can_be_contacted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="can_be_contacted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_data_be_shared",
            field=models.BooleanField(default=False),
        ),
    ]
